### ISSUE TITLE
quit button

### ISSUE THREAD

**Issue by nuttmegg** [DillyzThe1/TimeJam#1]
quit button doesn't pop out like the other buttons and just moves over a bit

**Comment by impostor5875** [comment]
it worked before dillyz messed with how the animations work so that's a him problem

**Comment by DillyzThe1** [comment]
resolved as of 51d538d46cd0d0b684126611c9c7393d9a5bc4d1
(i renamed `quit hover` to `quit hover reanimated`, assuming it was under a weird name for the system. i then realized that `quit hover reanimated` existed under the root folder, which means impostor placed them in the wrong spots himself.)
