### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Zarzok648GD** [DillyzThe1/TimeJam#2]
gaem is so repetive!!! how am i suposd to playye?????

**Comment by DillyzThe1** [comment]
![image](https://user-images.githubusercontent.com/34419642/218345654-e888fc17-8936-4167-9140-b971e33680e0.png)

**Comment by impostor5875** [comment]
eyaah!! it keep s restarting over adn over again!!! ahow do you gwt to the next levle?/??/!
